# Generated by Django 4.2.7 on 2023-11-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_alter_person_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
