# Generated by Django 5.0rc1 on 2023-11-30 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_comment_created_comment_updated_movie_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title_orig']},
        ),
    ]
