# Generated by Django 5.0rc1 on 2023-12-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_alter_movie_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
    ]
